apiVersion: v1
kind: Pod
metadata:
  - name: pod-sidecar-container
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html
          mountPath: /user/share/nginx/html
    - name: debug
      image: docker.io/rkalluru/learnk8s:side-car-html-generator
      volumeMounts:
        - name: html
          mountPath: /mnt/html
  volumes:
    - name: html
      emptyDir: {}