apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update
  labels:
    app: nginx
    env: dev
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.24

